export const projects = [
    {
        slug:"rambagh-mahal",
        name:"Rambagh Mahal",
        bgImg: "/rambagh.jpg",
        video: "https://www.youtube.com/embed/Z4ERfjwOJcs",
        description1: "Rambagh Mahal is one of the largest and most luxurious banquet venues, designed to make your special occasions unforgettable. With a seating capacity of up to 2000 guests, our grand banquet hall provides ample parking space for your convenience. Spanning a total area of 22,000 sq. ft., our venue features a stunning 15,000 sq. ft. main hall, a 7,000 sq. ft. upstairs mini hall, and an expansive 10,000 sq. ft. outdoor garden area, offering the perfect setting for any event.",
        description2: "Rambagh Mahal, a luxury banquet venue specializing in creating unforgettable events. Come visit us to experience our grandeur firsthand and see what we're all about! Special thanks to Rg Creations Nepal for their exceptional architectural design and complete construction support in bringing Rambagh Mahal to life as a Rambagh Mahal – Best Banquet and Party Palace in Kathmandu",
        location: "Bhanimandal, Lalitpur",
        contact: "+977-9802357234",
        category:"Banquet Hall & Party Palace",
        projectDemand: "Interior & Exterior",
        website: "https://rambaghmahal.com/"
    },
    {
        slug:"harshah-batika",
        name:"Harshah Batika",
        bgImg: "/media1.jpg",
        video: "https://www.youtube.com/embed/Org4L459RsI",
        description1: "Harshah Batika is a serene and family- friendly party venue in Kathmandu, spanning over 11 ropani of land. It features a charming Neo-Classical architectural design, making it ideal for various events, including corporate meetings and weddings. With elegant interiors and state-of-the-art facilities, it promises meticulous planning and exceptional service for an unforgettable experience.",
        description2: "Harshah Batika is in Balkumari, Lalitpur, Nepal. It is a luxurious and top banquet and wedding venue showcasing neo-classical architecture with ornate marble, and arched balconies. It features opulent wedding halls, world-class dining, lush gardens, and regal experiences like vintage decorations and interiors. Known for hosting iconic features, Harsha Batika offers a unique blend of luxury, and royal charm, making it a premier destination for people seeking a grand experience for any kinds of social events like wedding, receptions, weaning and many other ceremonies.",
        location: "Balkumari, Lalitpur",
        contact: "+977-9802357232",
        category:" Luxurious and top banquet and wedding venue",
        projectDemand: "Interior & Exterior",
         website: "https://harshahbatika.com/"
    },
    {
        slug:"royal-empire-boutique-hotel",
        name:"Royal Empire Boutique Hotel",
        bgImg: "/ImageVideo/Image4.jpg",
        video: "",
        description1: "Royal Empire Boutique Hotel is the ideal choice for a memorable stay in the vibrant city of Kathmandu. As you step into the hotel, you will be greeted by a warm and friendly staff, ready to cater to your every need. With a total of 15 well-appointed rooms, each thoughtfully designed to provide a tranquil oasis amidst the bustling city, you are guaranteed a peaceful and restful night's sleep. The rooms are tastefully decorated with modern amenities and feature comfortable beds, ensuring that you wake up refreshed and ready to explore all that Kathmandu has to offer. ",
        description2: "At Royal Empire Boutique Hotel, we believe in providing our guests with a truly unforgettable experience. That's why we offer a range of entertainment facilities designed to help you unwind and indulge during your stay in Kathmandu, Nepal. Step into our stylish bar, where you can sip on expertly crafted cocktails and enjoy a vibrant atmosphere. Whether you're looking to socialize with fellow travelers or simply relax with a drink after a long day of exploring, our bar is the perfect place to unwind. For those seeking ultimate relaxation, our steamroom is the ideal retreat. Indulge in the soothing heat and let the steam envelop your senses, melting away any stress or tension. Our lush garden provides a tranquil oasis amidst the bustling city. Take a leisurely stroll amidst the vibrant flora, or find a quiet spot to sit and enjoy a book. For the more playful guests, our games room offers a variety of exciting activities to keep you entertained. Challenge your friends to a game of pool or try your hand at darts, ensuring endless hours of fun and laughter. And if you're feeling particularly adventurous, our karaoke room awaits. Sing your heart out to your favorite tunes and let your inner superstar shine. At Royal Empire Boutique Hotel, we understand the importance of providing top-notch entertainment facilities to enhance your stay. So come and experience our exceptional offerings, and create memories that will last a lifetime.",
        location: "Baluwatar, Kathmandu",
        contact: "+977-01-4000542",
        category:"Luxury Hotel",
        projectDemand: "Interior & Exterior",
        website: "https://royal-empire-boutique.kathmandubesthotels.com/en/"
    },
    {
        slug:"club-deja-vu",
        name:"Club Deja vu",
        bgImg: "/ImageVideo/Image5.jpg",
        video: "https://www.youtube.com/embed/KL6GjVHCRS0",
        description1: "Déjà Vu Lounge, located in Durbar Marg, Kathmandu, offers a vibrant nightlife experience with a dance club atmosphere and gourmet dining. As an upscale venue, it caters to locals and tourists seeking memorable evenings. With a focus on entertainment and special events, Déjà Vu Lounge promotes active engagement on social media, showcasing its inviting ambiance and upcoming nightlife happenings.",
        description2: "One of the trendiest entertainment destinations, Deja Vu offers an immersive nightlife experience. Designed with dynamic lighting, sound acoustics, and premium lounge areas, it caters to a modern and energetic clientele. ",
        location: "Bhanimandal, Lalitpur",
        contact: "+977-01-4440744",
        category:"Nighclun & Lounge",
        projectDemand: "Interior & Exterior Construction",
         website: "https://www.facebook.com/dejavuktm/"
    },
    {
        slug:"magestic-grand-nepal",
        name:"Majestic Grand Nepal",
        bgImg: "/about/majestic.jpg",
        video: "https://www.youtube.com/embed/8-x2IvYZ9Og",
        description1: "The Majestic Grand is a beautifully designed banquet hall ideal for special occasions. It features elegant decor and a charming ambiance, enhancing the overall experience for guests. With convenient access to nearby attractions, the venue offers comprehensive event planning assistance, catering, and transportation arrangements, ensuring that each celebration is memorable and fits within budget.",
        description2: "The Majestic Grand Gallery provides unforgettable memories are captured in the most elegant setting. As the best events venue in Lalitpur, we take immense pride in hosting some of the most stunning weddings, grand receptions, corporate functions, and social celebrations in Nepal.",
        contact: "+977-9802357236",
        category:"Luxurious and top banquet and wedding venue",
        projectDemand: "Interior & Exterior Construction",
        website:"https://majesticgrandnepal.com/"
    },
    {
        slug:"boudha-heritage",
        name:"Boudha Heritage",
        bgImg: "/bouddha.jpg",
        video: "",
        description1: "Boudha Heritage in Kathmandu is a versatile venue perfect for weddings, receptions, and intimate gatherings, blending cultural richness with serenity. It offers various event services, including anniversaries and rice feeding ceremonies, fostering memorable celebrations. For bookings and inquiries, contact them via email or phone. The venue also shares visual highlights of recent events on social media, showcasing its unique charm.",
        description2: "It offers various event services, including anniversaries and rice feeding ceremonies, fostering memorable celebrations. For bookings and inquiries, contact them via email or phone. The venue also shares visual highlights of recent events on social media, showcasing its unique charm.",
        location: "Boudha, Kathmandu",
        contact: "+977-9803848330",
        category:"Banquet Hall & Party Palace",
        projectDemand: "Interior & Exterior",
         website: "https://www.facebook.com/boudhaheritage1/"
    },
    {
        slug:"imperial-banquet",
        name:"Imperial Banquet",
        bgImg: "/media2.jpeg",
        video: "",
        description1: "The Imperial Banquet is an opulent feast held to celebrate significant events or dignitaries in a monarchy. Attendees included nobility and esteemed guests, with an extravagant menu showcasing rare delicacies and fine wines. The banquet featured artistic presentations, performances, and elaborate decorations, reflecting the empire's wealth and cultural heritage. It served both as a diplomatic gesture and a display of power and prestige.",
        description2: "This chain of banquet halls across three major cities delivers uniform excellence in service and aesthetics. Each location is crafted to accommodate large crowds with high-end décor, lighting, and full-scale event management facilities. Imperial Banquet provide you a wide variety of menu items you can choose from. If you prefer selecting menu items with your loved ones at home, we have got just the right tool for you. Use our online booking and menu selection feature, sit back,  relax, and enjoy the process.",
        location: "Chabahil, Bhaktapur, Itahari",
        contact: "+977-9801881672",
        category:"Banquet Hall & Party Palace",
        projectDemand: "Interior & Exterior",
         website: "https://imperialbanquetnepal.com/"
    },
    {
        slug:"faces-lounge",
        name:"Faces Lounge",
        bgImg: "/faces.jpg",
        video: "",
        description1: "A stylish urban lounge that blends comfort, ambiance, and design. Faces Lounge is a popular social spot known for its inviting interiors, vibrant vibe, and focus on experience-based design elements.",
        description2: "Faces Lounge is a restaurant, bar and lounge with variety musical bands performing live music every evening and a late night club.",
        location: "Thamel, Kathmandu",
        contact: "+977-9843144638",
        category:"Restaurant, bar and lounge",
        projectDemand: "Interior & Exterior",
         website: "https://www.tripadvisor.com/Restaurant_Review-g293890-d5981039-Reviews-Faces_Lounge-Kathmandu_Kathmandu_Valley_Bagmati_Zone_Central_Region.html"
    },
    {
        slug:"victory-lounge",
        name:"Victory Lounge",
        bgImg: "/victory.jpg",
        video: "",
        description1: "Victory Lounge is a high-end lounge bar project focused on luxury entertainment. With bold lighting, plush seating, and signature design features, it offers an elite experience for the nightlife crowd.",
        description2: "Victory Restaurant & Lounge was born out of an idea to create a place where people could enjoy 5-Star meals in a relaxing, welcoming environment.  Ricardo, a decorated businessman, had visions of opening an elite restaurant with an ambiance Miami had never seen before. The mixture of a dynamic ambiance, unmatched vibe, impeccable food and hookah came to life with Victory Restaurant & Lounge.",
        location: "kathmandu",
        contact: "+977-9840581889",
        category:"Restaurant, bar and lounge",
        projectDemand: "Interior & Exterior",
         website: "https://www.facebook.com/lounge.victory/"
    },
    {
        slug:"station-pub",
        name:"Station Pub",
        bgImg: "/station.jpg",
        video: "",
        description1: "Designed with an industrial-modern aesthetic, Station Pub is a lively urban venue ideal for casual hangouts and weekend get-togethers. The design prioritizes functionality, edgy visuals, and a vibrant atmosphere.",
        description2: "Station Pub is a gem in the bustling city of Kathmandu, where locals and tourists alike gather to unwind and enjoy a laid-back atmosphere. This bar features a cozy interior and a welcoming outdoor space, perfect for sipping on a range of beverages—from classic cocktails to local brews. The ambiance is relaxed, making it an ideal spot to take a break from your busy sightseeing schedule. The pub is known for its friendly staff, who are always ready to recommend the best drinks to suit your taste.",
        location: "kathmandu",
        contact: "+977-9819052751",
        category:"Restaurant, bar and lounge",
        projectDemand: "Interior & Exterior",
         website: "https://evendo.com/locations/nepal/gosaikunda/bar/station-pub",
          images: [
            "/station1.jpg",
            "/station2.jpg",
  ]
    },
    {
        slug:"panas-banquet-event-hall",
        name:"Panas Banquet and Event Hall",
        bgImg: "/panas.jpg",
        video: "",
        description1: "A multifunctional event venue with modern design sensibilities, Panas Banquet is suitable for weddings, social gatherings, and business functions. Its flexible layout and elegant finish make it a favorite for diverse occasions.",
        description2: "Panas Events & Banquet, one of the finest party venue located in the heart of Kathmandu City(Capital) at Ringroad Basundhara having 15000 Sq. Ft Area with multistory double deck fabulous, well decorated indoor-hall. We comfortably can serve 2000+ people at a time. This is our capacity which we believe is our Strength. Parking for the bikes are available at our basement along with few cars. Besides, parking can also be done alongside Ringroad area at open space.",
        location: "Kathmandu",
        contact: "+977-01-4970941",
        category:"Banquet Hall & Party Palace",
        projectDemand: "Interior & Exterior",
         website: "https://panasbanquet.com/"
    },
    
]